name: fb_bot
channels:
  - defaults
dependencies:
  - brotlicffi=1.0.9.2=py310h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - certifi=2025.8.3=py310hecd8cb5_0
  - cffi=1.17.1=py310h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - expat=2.7.1=h6d0c2b6_0
  - idna=3.7=py310hecd8cb5_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.2=pyhc872135_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - python=3.10.18=hc958d9f_0
  - readline=8.3=h49f2429_0
  - requests=2.32.4=py310hecd8cb5_0
  - setuptools=78.1.1=py310hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310hecd8cb5_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
      - apify-client==2.3.0
      - apify-shared==2.1.0
      - colorama==0.4.6
      - impit==0.9.2
      - more-itertools==10.8.0
      - python-dotenv==1.2.1
prefix: /Users/levanpetrosian/miniconda3/envs/fb_bot
